project name: "work project"
path: ~/mogent

langs/stack: rust, tauri, nodejs, 

[[defaults]]
org: jobstore/managament

[[workflow]]
decision_id:
thought_experienct
spec_heavy
test_driven 

[[workflow.code]]
rust #verbose

[[style.chat]]
dyslexic-tts-friendly
teacherbot

[[style.code]]
ponytail

[[style.docs]]
caveman

